[package]
name = "rust-ts-experiments"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter = "0.20.1"
# tree-sitter-parsers = "0.0.5"

[build-dependencies]
cc = "1.0"
