type CBool = Bool
type CChar = Char
type CInt = Int
type CString = String
type CVoid = ()
type CMaybe = Maybe String
type CList = [Int]
type C1Tuple = (Char)
type C2Tuple = (Int, Char)
type C3Tuple = (String, Char, Bool)
type CNestedList = [[Int]]
type CNestedTuple = (String, (Int, Int))
type CNestedMixed = ([Int], (Char, Bool))
type CFunction = Bool -> Int
type CFunctionList = Int -> [String]
type CFunctionTuple = (Int, Int) -> Char
type CFunctionNested = (Int -> Char) -> [Int] -> [Char]
type CFunctionMixed = (Int -> (Char, String)) -> [Int] -> [(Char, String)]
